### ISSUE TITLE
work to be done

### ISSUE THREAD

**Issue by mike-kaufman** [Microsoft/node-diagnostic-channel#2]
Initial cut, will open issues on below as appropriate. 

- [x] rename to node-diagnostic-source
- [x] rename packages to diagnostic-source (PR #3)
- [ ] naming convention for publisher modules?  (e.g., `console-diagnostic-pub`? `console-diagnostic-source`?...)
 - [ ] test plan for how we don't break AI
 - [ ] test plan for how we don't break glimpse
 - [x] setup CI
 - [ ] get CI running across multiple node versions
 - [ ] get CI running across multiple module versions
 - [ ] figure out matrix above (what node versions X what module versions)
 - [x] don't write build output into source tree (PR #1)
 - [ ] ~~renaming magic variable used for auto-load~~ *(no longer needed per PR #15)*
 - [x] figure out publishing to NPM
 - [x] root level readme
 
**Glimpse:**
 - [ ] remove glimpse tracing APIs and replace with channel
   - [ ] add hrtime property to event
 - [ ] ...
 - [ ]

**AI:**
 - [ ] hook this up into AI SDK
 - [ ] move subs out
